# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FunctionDialog.ui'
#
# Created: Sat Mar  3 10:53:42 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_FunctionDialog(object):
    def setupUi(self, FunctionDialog):
        FunctionDialog.setObjectName(_fromUtf8("FunctionDialog"))
        FunctionDialog.resize(421, 542)
        self.verticalLayout_3 = QtGui.QVBoxLayout(FunctionDialog)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioButtonPeriodic = QtGui.QRadioButton(FunctionDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.radioButtonPeriodic.setFont(font)
        self.radioButtonPeriodic.setChecked(True)
        self.radioButtonPeriodic.setObjectName(_fromUtf8("radioButtonPeriodic"))
        self.horizontalLayout_2.addWidget(self.radioButtonPeriodic)
        self.label = QtGui.QLabel(FunctionDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setItalic(True)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.groupBox = QtGui.QGroupBox(FunctionDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.editA = QtGui.QLineEdit(self.groupBox)
        self.editA.setObjectName(_fromUtf8("editA"))
        self.gridLayout.addWidget(self.editA, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.editB = QtGui.QLineEdit(self.groupBox)
        self.editB.setObjectName(_fromUtf8("editB"))
        self.gridLayout.addWidget(self.editB, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButtonCustom = QtGui.QRadioButton(FunctionDialog)
        self.radioButtonCustom.setObjectName(_fromUtf8("radioButtonCustom"))
        self.verticalLayout_2.addWidget(self.radioButtonCustom)
        self.label_4 = QtGui.QLabel(FunctionDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.label_5 = QtGui.QLabel(FunctionDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setItalic(True)
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.groupBox_2 = QtGui.QGroupBox(FunctionDialog)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.editCustom = QtGui.QLineEdit(self.groupBox_2)
        self.editCustom.setObjectName(_fromUtf8("editCustom"))
        self.horizontalLayout_4.addWidget(self.editCustom)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.startTimeLabel = QtGui.QLabel(self.groupBox_2)
        self.startTimeLabel.setObjectName(_fromUtf8("startTimeLabel"))
        self.horizontalLayout.addWidget(self.startTimeLabel)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.endTimeEdit = QtGui.QLineEdit(self.groupBox_2)
        self.endTimeEdit.setObjectName(_fromUtf8("endTimeEdit"))
        self.horizontalLayout.addWidget(self.endTimeEdit)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        spacerItem2 = QtGui.QSpacerItem(188, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.addStep = QtGui.QPushButton(self.groupBox_2)
        self.addStep.setObjectName(_fromUtf8("addStep"))
        self.horizontalLayout_3.addWidget(self.addStep)
        self.deleteStep = QtGui.QPushButton(self.groupBox_2)
        self.deleteStep.setObjectName(_fromUtf8("deleteStep"))
        self.horizontalLayout_3.addWidget(self.deleteStep)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(78, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 0, 1, 1)
        self.TableCustomFunc = QtGui.QTableWidget(self.groupBox_2)
        self.TableCustomFunc.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TableCustomFunc.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.TableCustomFunc.setObjectName(_fromUtf8("TableCustomFunc"))
        self.TableCustomFunc.setColumnCount(3)
        self.TableCustomFunc.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.TableCustomFunc.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.TableCustomFunc.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.TableCustomFunc.setHorizontalHeaderItem(2, item)
        self.TableCustomFunc.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.TableCustomFunc, 1, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.line = QtGui.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.EditInterpStep = QtGui.QLineEdit(self.groupBox_2)
        self.EditInterpStep.setObjectName(_fromUtf8("EditInterpStep"))
        self.horizontalLayout_5.addWidget(self.EditInterpStep)
        self.ShowInterp_Button = QtGui.QPushButton(self.groupBox_2)
        self.ShowInterp_Button.setObjectName(_fromUtf8("ShowInterp_Button"))
        self.horizontalLayout_5.addWidget(self.ShowInterp_Button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        spacerItem5 = QtGui.QSpacerItem(400, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.buttonBox = QtGui.QDialogButtonBox(FunctionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(FunctionDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), FunctionDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), FunctionDialog.reject)
        QtCore.QObject.connect(self.radioButtonPeriodic, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox.setEnabled)
        QtCore.QObject.connect(self.radioButtonPeriodic, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox_2.setDisabled)
        QtCore.QObject.connect(self.radioButtonCustom, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox.setDisabled)
        QtCore.QObject.connect(self.radioButtonCustom, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox_2.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(FunctionDialog)
        FunctionDialog.setTabOrder(self.editA, self.editB)
        FunctionDialog.setTabOrder(self.editB, self.endTimeEdit)
        FunctionDialog.setTabOrder(self.endTimeEdit, self.addStep)
        FunctionDialog.setTabOrder(self.addStep, self.deleteStep)
        FunctionDialog.setTabOrder(self.deleteStep, self.editCustom)
        FunctionDialog.setTabOrder(self.editCustom, self.radioButtonPeriodic)
        FunctionDialog.setTabOrder(self.radioButtonPeriodic, self.buttonBox)
        FunctionDialog.setTabOrder(self.buttonBox, self.radioButtonCustom)
        FunctionDialog.setTabOrder(self.radioButtonCustom, self.EditInterpStep)
        FunctionDialog.setTabOrder(self.EditInterpStep, self.ShowInterp_Button)

    def retranslateUi(self, FunctionDialog):
        FunctionDialog.setWindowTitle(QtGui.QApplication.translate("FunctionDialog", "Define Function", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonPeriodic.setText(QtGui.QApplication.translate("FunctionDialog", "Periodic Function:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FunctionDialog", "F=A*sin(w*t)+B*cos(w*t)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("FunctionDialog", "Periodic Function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FunctionDialog", "A=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FunctionDialog", "B=", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonCustom.setText(QtGui.QApplication.translate("FunctionDialog", "Custom Function:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FunctionDialog", "Define function with parameters w,t by using Python notation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("FunctionDialog", "For example enter in the text box below: 20*sin(w*t)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("FunctionDialog", "Custom Function", None, QtGui.QApplication.UnicodeUTF8))
        self.startTimeLabel.setText(QtGui.QApplication.translate("FunctionDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("FunctionDialog", "<= time <", None, QtGui.QApplication.UnicodeUTF8))
        self.endTimeEdit.setText(QtGui.QApplication.translate("FunctionDialog", "10000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("FunctionDialog", "[sec]", None, QtGui.QApplication.UnicodeUTF8))
        self.addStep.setText(QtGui.QApplication.translate("FunctionDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteStep.setText(QtGui.QApplication.translate("FunctionDialog", "Remove Last", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableCustomFunc.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("FunctionDialog", "Start time", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableCustomFunc.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("FunctionDialog", "End time", None, QtGui.QApplication.UnicodeUTF8))
        item = self.TableCustomFunc.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("FunctionDialog", "Function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setToolTip(QtGui.QApplication.translate("FunctionDialog", "<html><head/><body><p><span style=\" font-style:italic;\">Set this value small enough to capture behaviour of your function</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("FunctionDialog", "Interp. Step [sec]:", None, QtGui.QApplication.UnicodeUTF8))
        self.EditInterpStep.setToolTip(QtGui.QApplication.translate("FunctionDialog", "<html><head/><body><p><span style=\" font-style:italic;\">Set this value small enough to capture behaviour of your function</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.EditInterpStep.setText(QtGui.QApplication.translate("FunctionDialog", "0.01", None, QtGui.QApplication.UnicodeUTF8))
        self.ShowInterp_Button.setText(QtGui.QApplication.translate("FunctionDialog", "Show", None, QtGui.QApplication.UnicodeUTF8))

