# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oddsFormMain.ui'
#
# Created: Sat May 19 21:05:40 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(909, 601)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Trebuchet MS"))
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShadow(QtGui.QFrame.Raised)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        self.nodes_spinBox = QtGui.QSpinBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nodes_spinBox.sizePolicy().hasHeightForWidth())
        self.nodes_spinBox.setSizePolicy(sizePolicy)
        self.nodes_spinBox.setObjectName(_fromUtf8("nodes_spinBox"))
        self.horizontalLayout_7.addWidget(self.nodes_spinBox)
        spacerItem = QtGui.QSpacerItem(488, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.testODE = QtGui.QPushButton(self.tab)
        self.testODE.setObjectName(_fromUtf8("testODE"))
        self.horizontalLayout_7.addWidget(self.testODE)
        self.printSyst = QtGui.QPushButton(self.tab)
        self.printSyst.setObjectName(_fromUtf8("printSyst"))
        self.horizontalLayout_7.addWidget(self.printSyst)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.line_4 = QtGui.QFrame(self.tab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_7.addWidget(self.line_4)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Trebuchet MS"))
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFrameShadow(QtGui.QFrame.Plain)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        spacerItem1 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.MassAddButton = QtGui.QPushButton(self.tab)
        self.MassAddButton.setObjectName(_fromUtf8("MassAddButton"))
        self.horizontalLayout_6.addWidget(self.MassAddButton)
        self.MassEditButton = QtGui.QPushButton(self.tab)
        self.MassEditButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.MassEditButton.setObjectName(_fromUtf8("MassEditButton"))
        self.horizontalLayout_6.addWidget(self.MassEditButton)
        self.MassDeleteButton = QtGui.QPushButton(self.tab)
        self.MassDeleteButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.MassDeleteButton.setObjectName(_fromUtf8("MassDeleteButton"))
        self.horizontalLayout_6.addWidget(self.MassDeleteButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.MassTable = QtGui.QTableWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MassTable.sizePolicy().hasHeightForWidth())
        self.MassTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.MassTable.setFont(font)
        self.MassTable.setObjectName(_fromUtf8("MassTable"))
        self.MassTable.setColumnCount(2)
        self.MassTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.MassTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.MassTable.setHorizontalHeaderItem(1, item)
        self.MassTable.horizontalHeader().setStretchLastSection(False)
        self.MassTable.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.MassTable)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Trebuchet MS"))
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.DispAddButton = QtGui.QPushButton(self.tab)
        self.DispAddButton.setObjectName(_fromUtf8("DispAddButton"))
        self.horizontalLayout_3.addWidget(self.DispAddButton)
        self.DispEditButton = QtGui.QPushButton(self.tab)
        self.DispEditButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DispEditButton.setObjectName(_fromUtf8("DispEditButton"))
        self.horizontalLayout_3.addWidget(self.DispEditButton)
        self.DispDelButton = QtGui.QPushButton(self.tab)
        self.DispDelButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DispDelButton.setObjectName(_fromUtf8("DispDelButton"))
        self.horizontalLayout_3.addWidget(self.DispDelButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.DispTable = QtGui.QTableWidget(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.DispTable.setFont(font)
        self.DispTable.setObjectName(_fromUtf8("DispTable"))
        self.DispTable.setColumnCount(4)
        self.DispTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.DispTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.DispTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.DispTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.DispTable.setHorizontalHeaderItem(3, item)
        self.DispTable.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.DispTable)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_6.addWidget(self.line_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Trebuchet MS"))
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFrameShadow(QtGui.QFrame.Plain)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.ForceAddButton = QtGui.QPushButton(self.tab)
        self.ForceAddButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ForceAddButton.setObjectName(_fromUtf8("ForceAddButton"))
        self.horizontalLayout.addWidget(self.ForceAddButton)
        self.ForceEditButton = QtGui.QPushButton(self.tab)
        self.ForceEditButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ForceEditButton.setObjectName(_fromUtf8("ForceEditButton"))
        self.horizontalLayout.addWidget(self.ForceEditButton)
        self.ForceDeleteButton = QtGui.QPushButton(self.tab)
        self.ForceDeleteButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ForceDeleteButton.setObjectName(_fromUtf8("ForceDeleteButton"))
        self.horizontalLayout.addWidget(self.ForceDeleteButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.ForceTable = QtGui.QTableWidget(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.ForceTable.setFont(font)
        self.ForceTable.setObjectName(_fromUtf8("ForceTable"))
        self.ForceTable.setColumnCount(3)
        self.ForceTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.ForceTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.ForceTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.ForceTable.setHorizontalHeaderItem(2, item)
        self.ForceTable.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.ForceTable)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.line_2 = QtGui.QFrame(self.tab)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_5.addWidget(self.line_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Trebuchet MS"))
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem4 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.ConnAddButton = QtGui.QPushButton(self.tab)
        self.ConnAddButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ConnAddButton.setObjectName(_fromUtf8("ConnAddButton"))
        self.horizontalLayout_2.addWidget(self.ConnAddButton)
        self.ConnEditButton = QtGui.QPushButton(self.tab)
        self.ConnEditButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ConnEditButton.setObjectName(_fromUtf8("ConnEditButton"))
        self.horizontalLayout_2.addWidget(self.ConnEditButton)
        self.ConnDelButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConnDelButton.sizePolicy().hasHeightForWidth())
        self.ConnDelButton.setSizePolicy(sizePolicy)
        self.ConnDelButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ConnDelButton.setObjectName(_fromUtf8("ConnDelButton"))
        self.horizontalLayout_2.addWidget(self.ConnDelButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.ConnTable = QtGui.QTableWidget(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.ConnTable.setFont(font)
        self.ConnTable.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.ConnTable.setObjectName(_fromUtf8("ConnTable"))
        self.ConnTable.setColumnCount(4)
        self.ConnTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.ConnTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.ConnTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.ConnTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.ConnTable.setHorizontalHeaderItem(3, item)
        self.ConnTable.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.ConnTable)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.radioButton_SingleFreq = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_SingleFreq.setChecked(True)
        self.radioButton_SingleFreq.setObjectName(_fromUtf8("radioButton_SingleFreq"))
        self.verticalLayout_11.addWidget(self.radioButton_SingleFreq)
        self.radioButton_FreqSweep = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_FreqSweep.setObjectName(_fromUtf8("radioButton_FreqSweep"))
        self.verticalLayout_11.addWidget(self.radioButton_FreqSweep)
        self.verticalLayout_10.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.lineEdit_SingleFreq = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_SingleFreq.setObjectName(_fromUtf8("lineEdit_SingleFreq"))
        self.horizontalLayout_8.addWidget(self.lineEdit_SingleFreq)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.verticalLayout_10.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_FreqStart = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_FreqStart.setObjectName(_fromUtf8("lineEdit_FreqStart"))
        self.gridLayout.addWidget(self.lineEdit_FreqStart, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_FreqStop = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_FreqStop.setObjectName(_fromUtf8("lineEdit_FreqStop"))
        self.gridLayout.addWidget(self.lineEdit_FreqStop, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.lineEdit_FreqStep = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_FreqStep.setObjectName(_fromUtf8("lineEdit_FreqStep"))
        self.gridLayout.addWidget(self.lineEdit_FreqStep, 2, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout)
        self.verticalLayout_10.addWidget(self.groupBox_2)
        spacerItem5 = QtGui.QSpacerItem(20, 58, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem5)
        self.horizontalLayout_15.addLayout(self.verticalLayout_10)
        self.line_8 = QtGui.QFrame(self.tab_2)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout_15.addWidget(self.line_8)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.comboBox_DOF = QtGui.QComboBox(self.tab_2)
        self.comboBox_DOF.setObjectName(_fromUtf8("comboBox_DOF"))
        self.gridLayout_2.addWidget(self.comboBox_DOF, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.lineEdit_DispInit = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_DispInit.setObjectName(_fromUtf8("lineEdit_DispInit"))
        self.gridLayout_2.addWidget(self.lineEdit_DispInit, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 3, 0, 1, 1)
        self.lineEdit_VelInit = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_VelInit.setObjectName(_fromUtf8("lineEdit_VelInit"))
        self.gridLayout_2.addWidget(self.lineEdit_VelInit, 3, 1, 1, 1)
        self.tableWidgetInitCon = QtGui.QTableWidget(self.tab_2)
        self.tableWidgetInitCon.setObjectName(_fromUtf8("tableWidgetInitCon"))
        self.tableWidgetInitCon.setColumnCount(3)
        self.tableWidgetInitCon.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Serif"))
        font.setPointSize(10)
        font.setItalic(False)
        item.setFont(font)
        self.tableWidgetInitCon.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInitCon.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInitCon.setHorizontalHeaderItem(2, item)
        self.tableWidgetInitCon.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.tableWidgetInitCon, 4, 0, 1, 2)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_23 = QtGui.QLabel(self.tab_2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_11.addWidget(self.label_23)
        self.lineStartTime = QtGui.QLineEdit(self.tab_2)
        self.lineStartTime.setObjectName(_fromUtf8("lineStartTime"))
        self.horizontalLayout_11.addWidget(self.lineStartTime)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 5, 0, 1, 2)
        self.horizontalLayout_15.addLayout(self.gridLayout_2)
        self.line_6 = QtGui.QFrame(self.tab_2)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout_15.addWidget(self.line_6)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_14.addWidget(self.label_14)
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_14.addWidget(self.label_15)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_10.addWidget(self.label_16)
        self.lineEdit_Npeaks = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_Npeaks.setObjectName(_fromUtf8("lineEdit_Npeaks"))
        self.horizontalLayout_10.addWidget(self.lineEdit_Npeaks)
        self.comboBoxPeaks = QtGui.QComboBox(self.tab_2)
        self.comboBoxPeaks.setObjectName(_fromUtf8("comboBoxPeaks"))
        self.comboBoxPeaks.addItem(_fromUtf8(""))
        self.comboBoxPeaks.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.comboBoxPeaks)
        spacerItem6 = QtGui.QSpacerItem(208, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.verticalLayout_14.addLayout(self.horizontalLayout_10)
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_14.addWidget(self.label_17)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_9.addWidget(self.label_18)
        self.lineEdit_NpeaksSS = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_NpeaksSS.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_NpeaksSS.sizePolicy().hasHeightForWidth())
        self.lineEdit_NpeaksSS.setSizePolicy(sizePolicy)
        self.lineEdit_NpeaksSS.setObjectName(_fromUtf8("lineEdit_NpeaksSS"))
        self.horizontalLayout_9.addWidget(self.lineEdit_NpeaksSS)
        spacerItem7 = QtGui.QSpacerItem(208, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_14.addLayout(self.horizontalLayout_9)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.radioButton_constantNpeak = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_constantNpeak.setChecked(True)
        self.radioButton_constantNpeak.setObjectName(_fromUtf8("radioButton_constantNpeak"))
        self.horizontalLayout_14.addWidget(self.radioButton_constantNpeak)
        self.lineEdit_constNpeak = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_constNpeak.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_constNpeak.sizePolicy().hasHeightForWidth())
        self.lineEdit_constNpeak.setSizePolicy(sizePolicy)
        self.lineEdit_constNpeak.setObjectName(_fromUtf8("lineEdit_constNpeak"))
        self.horizontalLayout_14.addWidget(self.lineEdit_constNpeak)
        spacerItem8 = QtGui.QSpacerItem(120, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.verticalLayout_13.addWidget(self.groupBox_4)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_19 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_12.addWidget(self.label_19)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_20 = QtGui.QLabel(self.tab_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_12.addWidget(self.label_20)
        self.lineEdit_AbsError = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_AbsError.setEnabled(False)
        self.lineEdit_AbsError.setObjectName(_fromUtf8("lineEdit_AbsError"))
        self.horizontalLayout_12.addWidget(self.lineEdit_AbsError)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_12.addWidget(self.label_21)
        self.lineEdit_relError = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_relError.setEnabled(False)
        self.lineEdit_relError.setObjectName(_fromUtf8("lineEdit_relError"))
        self.horizontalLayout_12.addWidget(self.lineEdit_relError)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        spacerItem10 = QtGui.QSpacerItem(20, 78, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem10)
        self.horizontalLayout_15.addLayout(self.verticalLayout_14)
        self.verticalLayout_15.addLayout(self.horizontalLayout_15)
        self.line_7 = QtGui.QFrame(self.tab_2)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_15.addWidget(self.line_7)
        spacerItem11 = QtGui.QSpacerItem(20, 88, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem11)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.pushButton_Solve = QtGui.QPushButton(self.tab_2)
        self.pushButton_Solve.setObjectName(_fromUtf8("pushButton_Solve"))
        self.horizontalLayout_13.addWidget(self.pushButton_Solve)
        self.progressBar_Solution = QtGui.QProgressBar(self.tab_2)
        self.progressBar_Solution.setProperty("value", 0)
        self.progressBar_Solution.setObjectName(_fromUtf8("progressBar_Solution"))
        self.horizontalLayout_13.addWidget(self.progressBar_Solution)
        spacerItem12 = QtGui.QSpacerItem(248, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem12)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 909, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFIle = QtGui.QMenu(self.menubar)
        self.menuFIle.setObjectName(_fromUtf8("menuFIle"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFIle.addAction(self.actionOpen)
        self.menuFIle.addAction(self.actionSave)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.radioButton_SingleFreq, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox_2.setDisabled)
        QtCore.QObject.connect(self.radioButton_SingleFreq, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.groupBox.setEnabled)
        QtCore.QObject.connect(self.radioButton_FreqSweep, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox_2.setEnabled)
        QtCore.QObject.connect(self.radioButton_FreqSweep, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox.setDisabled)
        QtCore.QObject.connect(self.radioButton_constantNpeak, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_constNpeak.setEnabled)
        QtCore.QObject.connect(self.radioButton_SingleFreq, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_NpeaksSS.setDisabled)
        QtCore.QObject.connect(self.radioButton_FreqSweep, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_NpeaksSS.setEnabled)
        QtCore.QObject.connect(self.radioButton_FreqSweep, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboBox_DOF.setDisabled)
        QtCore.QObject.connect(self.radioButton_FreqSweep, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_DispInit.setDisabled)
        QtCore.QObject.connect(self.radioButton_FreqSweep, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_VelInit.setDisabled)
        QtCore.QObject.connect(self.radioButton_FreqSweep, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.tableWidgetInitCon.setDisabled)
        QtCore.QObject.connect(self.radioButton_FreqSweep, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineStartTime.setDisabled)
        QtCore.QObject.connect(self.radioButton_SingleFreq, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_DispInit.setEnabled)
        QtCore.QObject.connect(self.radioButton_SingleFreq, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.comboBox_DOF.setEnabled)
        QtCore.QObject.connect(self.radioButton_SingleFreq, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineEdit_VelInit.setEnabled)
        QtCore.QObject.connect(self.radioButton_FreqSweep, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.tableWidgetInitCon.setEnabled)
        QtCore.QObject.connect(self.radioButton_SingleFreq, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.lineStartTime.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ODDS - One Dimensional Dynamic Systems", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Number of nodes:", None, QtGui.QApplication.UnicodeUTF8))
        self.testODE.setText(QtGui.QApplication.translate("MainWindow", "SolveODE", None, QtGui.QApplication.UnicodeUTF8))
        self.printSyst.setText(QtGui.QApplication.translate("MainWindow", "Print Syst.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Masses:", None, QtGui.QApplication.UnicodeUTF8))
        self.MassAddButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.MassEditButton.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.MassDeleteButton.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        item = self.MassTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Node", None, QtGui.QApplication.UnicodeUTF8))
        item = self.MassTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Displacements:", None, QtGui.QApplication.UnicodeUTF8))
        self.DispAddButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.DispEditButton.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.DispDelButton.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        item = self.DispTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Node", None, QtGui.QApplication.UnicodeUTF8))
        item = self.DispTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        item = self.DispTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Function", None, QtGui.QApplication.UnicodeUTF8))
        item = self.DispTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Forces:", None, QtGui.QApplication.UnicodeUTF8))
        self.ForceAddButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.ForceEditButton.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.ForceDeleteButton.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        item = self.ForceTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Node", None, QtGui.QApplication.UnicodeUTF8))
        item = self.ForceTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Function", None, QtGui.QApplication.UnicodeUTF8))
        item = self.ForceTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Connectors:", None, QtGui.QApplication.UnicodeUTF8))
        self.ConnAddButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.ConnEditButton.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.ConnDelButton.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        item = self.ConnTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Start Node", None, QtGui.QApplication.UnicodeUTF8))
        item = self.ConnTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "End Node", None, QtGui.QApplication.UnicodeUTF8))
        item = self.ConnTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        item = self.ConnTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "System", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Choose Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_SingleFreq.setText(QtGui.QApplication.translate("MainWindow", "Single Frequency/ No Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_FreqSweep.setText(QtGui.QApplication.translate("MainWindow", "Frequency Sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Single Freq. Params", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Frequency [Hz]:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_SingleFreq.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Sweep Params", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Start [Hz]:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_FreqStart.setText(QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "End [Hz]:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_FreqStop.setText(QtGui.QApplication.translate("MainWindow", "40", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Step [Hz]:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_FreqStep.setText(QtGui.QApplication.translate("MainWindow", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Initial Conditions:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Choose DOF:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Displacement:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Velocity:", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetInitCon.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Node", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetInitCon.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Disp", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetInitCon.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Vel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Time Shift:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineStartTime.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Solver Parameters:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "End solution time / number of peaks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Peaks/time", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_Npeaks.setText(QtGui.QApplication.translate("MainWindow", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPeaks.setItemText(0, QtGui.QApplication.translate("MainWindow", "Peaks", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxPeaks.setItemText(1, QtGui.QApplication.translate("MainWindow", "Seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Number of last peaks to be consideres steady state:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "N_Peaks_SS:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_NpeaksSS.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Number of points per peak", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_constantNpeak.setText(QtGui.QApplication.translate("MainWindow", "NPeak", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_constNpeak.setText(QtGui.QApplication.translate("MainWindow", "2000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Integrator parameters:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Abs. Error:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_AbsError.setText(QtGui.QApplication.translate("MainWindow", "1.49012e-8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Rel. Error:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_relError.setText(QtGui.QApplication.translate("MainWindow", "1.49012e-8", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Solve.setText(QtGui.QApplication.translate("MainWindow", "SOLVE", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFIle.setTitle(QtGui.QApplication.translate("MainWindow", "FIle", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

