# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oddsForm.ui'
#
# Created: Sat Jan  7 11:47:29 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mainDialog(object):
    def setupUi(self, mainDialog):
        mainDialog.setObjectName(_fromUtf8("mainDialog"))
        mainDialog.resize(812, 493)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainDialog.sizePolicy().hasHeightForWidth())
        mainDialog.setSizePolicy(sizePolicy)
        self.verticalLayout_5 = QtGui.QVBoxLayout(mainDialog)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(mainDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Trebuchet MS"))
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShadow(QtGui.QFrame.Raised)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.nodes_spinBox = QtGui.QSpinBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nodes_spinBox.sizePolicy().hasHeightForWidth())
        self.nodes_spinBox.setSizePolicy(sizePolicy)
        self.nodes_spinBox.setObjectName(_fromUtf8("nodes_spinBox"))
        self.horizontalLayout_4.addWidget(self.nodes_spinBox)
        spacerItem = QtGui.QSpacerItem(578, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.line_4 = QtGui.QFrame(self.tab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_3.addWidget(self.line_4)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Trebuchet MS"))
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFrameShadow(QtGui.QFrame.Plain)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        spacerItem1 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.MassAddButton = QtGui.QPushButton(self.tab)
        self.MassAddButton.setObjectName(_fromUtf8("MassAddButton"))
        self.horizontalLayout_6.addWidget(self.MassAddButton)
        self.MassEditButton = QtGui.QPushButton(self.tab)
        self.MassEditButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.MassEditButton.setObjectName(_fromUtf8("MassEditButton"))
        self.horizontalLayout_6.addWidget(self.MassEditButton)
        self.MassDeleteButton = QtGui.QPushButton(self.tab)
        self.MassDeleteButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.MassDeleteButton.setObjectName(_fromUtf8("MassDeleteButton"))
        self.horizontalLayout_6.addWidget(self.MassDeleteButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.MassTable = QtGui.QTableWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MassTable.sizePolicy().hasHeightForWidth())
        self.MassTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.MassTable.setFont(font)
        self.MassTable.setObjectName(_fromUtf8("MassTable"))
        self.MassTable.setColumnCount(2)
        self.MassTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.MassTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.MassTable.setHorizontalHeaderItem(1, item)
        self.MassTable.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.MassTable)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 1, 3, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Trebuchet MS"))
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.DispAddButton = QtGui.QPushButton(self.tab)
        self.DispAddButton.setObjectName(_fromUtf8("DispAddButton"))
        self.horizontalLayout_3.addWidget(self.DispAddButton)
        self.DispEditButton = QtGui.QPushButton(self.tab)
        self.DispEditButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DispEditButton.setObjectName(_fromUtf8("DispEditButton"))
        self.horizontalLayout_3.addWidget(self.DispEditButton)
        self.DispDelButton = QtGui.QPushButton(self.tab)
        self.DispDelButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DispDelButton.setObjectName(_fromUtf8("DispDelButton"))
        self.horizontalLayout_3.addWidget(self.DispDelButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.DispTable = QtGui.QTableWidget(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.DispTable.setFont(font)
        self.DispTable.setObjectName(_fromUtf8("DispTable"))
        self.DispTable.setColumnCount(4)
        self.DispTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.DispTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.DispTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.DispTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.DispTable.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.DispTable)
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_2.addWidget(self.line_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Trebuchet MS"))
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem3 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.ConnAddButton = QtGui.QPushButton(self.tab)
        self.ConnAddButton.setObjectName(_fromUtf8("ConnAddButton"))
        self.horizontalLayout_2.addWidget(self.ConnAddButton)
        self.ConnEditButton = QtGui.QPushButton(self.tab)
        self.ConnEditButton.setObjectName(_fromUtf8("ConnEditButton"))
        self.horizontalLayout_2.addWidget(self.ConnEditButton)
        self.ConnDelButton = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConnDelButton.sizePolicy().hasHeightForWidth())
        self.ConnDelButton.setSizePolicy(sizePolicy)
        self.ConnDelButton.setObjectName(_fromUtf8("ConnDelButton"))
        self.horizontalLayout_2.addWidget(self.ConnDelButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.ConnTable = QtGui.QTableWidget(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.ConnTable.setFont(font)
        self.ConnTable.setObjectName(_fromUtf8("ConnTable"))
        self.ConnTable.setColumnCount(0)
        self.ConnTable.setRowCount(0)
        self.verticalLayout_2.addWidget(self.ConnTable)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 3, 1)
        spacerItem4 = QtGui.QSpacerItem(17, 178, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.printSyst = QtGui.QPushButton(self.tab)
        self.printSyst.setObjectName(_fromUtf8("printSyst"))
        self.horizontalLayout_5.addWidget(self.printSyst)
        spacerItem5 = QtGui.QSpacerItem(238, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget)

        self.retranslateUi(mainDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainDialog)

    def retranslateUi(self, mainDialog):
        mainDialog.setWindowTitle(QtGui.QApplication.translate("mainDialog", "1D Dynamical Systems", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mainDialog", "Number of nodes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("mainDialog", "Masses:", None, QtGui.QApplication.UnicodeUTF8))
        self.MassAddButton.setText(QtGui.QApplication.translate("mainDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.MassEditButton.setText(QtGui.QApplication.translate("mainDialog", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.MassDeleteButton.setText(QtGui.QApplication.translate("mainDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        item = self.MassTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("mainDialog", "Node", None, QtGui.QApplication.UnicodeUTF8))
        item = self.MassTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("mainDialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("mainDialog", "Displacements:", None, QtGui.QApplication.UnicodeUTF8))
        self.DispAddButton.setText(QtGui.QApplication.translate("mainDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.DispEditButton.setText(QtGui.QApplication.translate("mainDialog", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.DispDelButton.setText(QtGui.QApplication.translate("mainDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        item = self.DispTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("mainDialog", "Node", None, QtGui.QApplication.UnicodeUTF8))
        item = self.DispTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("mainDialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        item = self.DispTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("mainDialog", "Function", None, QtGui.QApplication.UnicodeUTF8))
        item = self.DispTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("mainDialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mainDialog", "Connectors:", None, QtGui.QApplication.UnicodeUTF8))
        self.ConnAddButton.setText(QtGui.QApplication.translate("mainDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.ConnEditButton.setText(QtGui.QApplication.translate("mainDialog", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.ConnDelButton.setText(QtGui.QApplication.translate("mainDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.printSyst.setText(QtGui.QApplication.translate("mainDialog", "Print Syst.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("mainDialog", "System", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("mainDialog", "VIbration", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("mainDialog", "Shock", None, QtGui.QApplication.UnicodeUTF8))

